### 模型评估

#### 实验任务

##### 实验背景

##### 实验目标

##### 实验思路

- 生成实验数据
- 代入数据集实现分类和回归的模型评估方法

##### 实验操作步骤

###### 步骤1 分类效果评价指标

In [ ]:
# accuracy_score = 预测正确的样本率/总样本率
import numpy as np
from sklearn.metrics import accuracy_score
y_pred = [0,2,1,3]
y_true = [0,1,2,3]

a = accuracy_score(y_true,y_pred)
b = accuracy_score(y_true,y_pred,normalize=False)
# 输出预测准确率
print(a,b)
#结果如下:

0.5 2


In [2]:
# 导入生成混淆矩阵的方法
from sklearn.metrics import confusion_matrix
# 多值类型
y_true = [2,0,2,2,0,1]
y_pred = [0,0,2,2,0,2]
#输出混淆矩阵
print(confusion_matrix(y_true,y_pred))

[[2 0 0]
 [0 0 1]
 [1 0 2]]


In [4]:
# 二值类型
y_true = [0,0,0,1,1,1,1,1]
y_pred = [0,1,0,1,0,1,0,1]
print(confusion_matrix(y_true,y_pred))

[[2 1]
 [2 3]]


In [5]:
tn,fp,fn,tp = confusion_matrix(y_true,y_pred).ravel()
print(tn,fp,fn,tp)

2 1 2 3


In [6]:
# 查准率
from sklearn import metrics
y_pred = [0,1,0,0]
y_true = [0,1,0,1]
metrics.precision_score(y_true,y_pred)  # precision = tp/(tp+fp)

1.0

In [7]:
# 召回率查看
metrics.recall_score(y_true,y_pred)

0.5

In [8]:
metrics.f1_score(y_true,y_pred)

0.6666666666666666

In [9]:
metrics.fbeta_score(y_true,y_pred,beta=0.5)

0.8333333333333334

In [10]:
metrics.fbeta_score(y_true,y_pred,beta=1)

0.6666666666666666

In [11]:
metrics.fbeta_score(y_true,y_pred,beta=2)

0.5555555555555556

In [12]:
from sklearn.metrics import classification_report
y_true = [0,1,2,2,0]
y_pred = [0,0,2,1,0]
target_names = ['class 0','class 1','class 2']
print(classification_report(y_true,y_pred,target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.67      1.00      0.80         2
     class 1       0.00      0.00      0.00         1
     class 2       1.00      0.50      0.67         2

    accuracy                           0.60         5
   macro avg       0.56      0.50      0.49         5
weighted avg       0.67      0.60      0.59         5



In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import BaggingClassifier,AdaBoostClassifier,GradientBoostingClassifier,RandomForestClassifiert X
from xgboost.sklearn import XGB