In [1]:
# 数据基础
import math

In [2]:
math.ceil(4.5)

5

In [3]:
a = math.ceil(45.34)

In [4]:
print(a)

46


In [5]:
import numpy as np

In [6]:
math.floor(4.5)

4

In [7]:
math.cos(math.pi/3)

0.5000000000000001

In [8]:
math.tan(math.pi/4)

0.9999999999999999

In [9]:
# degrees x 把弧度转成角度
math.degrees(math.pi/3)

59.99999999999999

In [10]:
math.degrees(math.pi/4)

45.0

In [11]:
math.degrees(math.pi)

180.0

In [12]:
math.pi

3.141592653589793

In [13]:
math.exp

<function math.exp(x, /)>

In [14]:
math.exp(e)

NameError: name 'e' is not defined

In [15]:
math.exp(2.78)

16.119020948027543

In [16]:
math.exp(1)

2.718281828459045

In [17]:
math.exp(2)

7.38905609893065

In [18]:
# fabs 返回绝对值

math.fabs(-1)

1.0

In [19]:
#fabs(x) 返回x的绝对值

In [20]:
math.fabs(-0.03)

0.03

In [22]:
# factorical 取x的阶乘的值

math.factorial(2)

2

In [23]:
math.factorial(3)

6

In [24]:
math.factorial(4)

24

In [25]:
math.factorial(100)

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000

In [26]:
math.factorial(4)

24

In [27]:
!clear


In [28]:
a = [1,2,3]
math.fsum(a)

6.0

In [29]:
# fsum(interable)对迭代器的每个元素进行求和操作

In [30]:
math.fmod(20,2)

0.0

In [31]:
math.fmod(20,3)

2.0

In [32]:
math.log(10)

2.302585092994046

In [ ]:
#log([x,base])

In [35]:
math.log(1)

0.0

In [36]:
math.log(math.e)

1.0

In [37]:
math.e

2.718281828459045

In [38]:
math.sqrt(100)

10.0

In [39]:
math.sqrt(1.44)

1.2

In [40]:
math.pow(12,2)

144.0

In [41]:
# trunc实现返回x的整数部分

In [42]:
math.trunc(2.3)

2

In [43]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
np.arange(12).shape

(12,)

In [46]:
x = np.arange(16)

In [47]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
A = np.arange(12).reshape(3,4)

In [55]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
A.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [58]:
B = np.arange(8).reshape(2,4)

In [59]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [60]:
C = B.T

In [61]:
print(C)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [62]:
C

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [63]:
A = np.arange(6).reshape(3,2)
B = np.arange(6).reshape(2,3)
np.matmul(A,B)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [64]:
np.matmul(B,A)

array([[10, 13],
       [28, 40]])

In [65]:
A = np.arange(12).reshape(3,4)
A+A

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [66]:
A = np.arange(6).reshape(3,2)

In [67]:
print(A*A)

[[ 0  1]
 [ 4  9]
 [16 25]]


In [71]:
C = np.arange(16).reshape(4,4)

In [72]:
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# 只有偶方矩阵才有逆矩阵

In [74]:
np.linalg.inv(C)

array([[ 9.00719925e+14, -4.50359963e+14, -1.80143985e+15,
         1.35107989e+15],
       [-2.40191980e+15,  2.70215978e+15,  1.80143985e+15,
        -2.10167983e+15],
       [ 2.10167983e+15, -4.05323966e+15,  1.80143985e+15,
         1.50119988e+14],
       [-6.00479950e+14,  1.80143985e+15, -1.80143985e+15,
         6.00479950e+14]])

In [75]:
np.linalg.inv(np.arange(64).reshape(8,8))

LinAlgError: Singular matrix

In [80]:
D = np.arange(4).reshape(2,2)

In [81]:
D

array([[0, 1],
       [2, 3]])

In [82]:
np.linalg.inv(D)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])